name: namer
description: A simple package to produce random strings to name things.
version: 1.0.0
repository: https://github.com/jtmcdole/namer

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
